# Generated by Django 5.2.8 on 2025-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_alter_employer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
